import shutil
import os

print("[+] Cleaning old generated data...")

for path in ["build", "outputs"]:
    if os.path.exists(path):
        shutil.rmtree(path)

os.makedirs("build/iocs", exist_ok=True)
os.makedirs("build/pcaps", exist_ok=True)
os.makedirs("build/vulnerabilities", exist_ok=True)
os.makedirs("outputs/charts", exist_ok=True)
os.makedirs("outputs/logs", exist_ok=True)
os.makedirs("outputs/reports", exist_ok=True)

from src.ingestion.threat_feed_pull import pull_osint_iocs
from src.analysis.pcap_parser import parse_pcap
from src.analysis.ioc_correlation import correlate_iocs
from src.analysis.risk_scoring import score_vulnerabilities
from src.reporting.generate_charts import generate_top_ip_chart
import os
import csv
from scapy.all import Ether, IP, TCP, wrpcap

# --- Paths ---
IOC_PATH = "build/iocs/osint_iocs.csv"
PCAP_PATH = "build/pcaps/sample_traffic.pcap"
VULN_PATH = "build/vulnerabilities/vuln_scan_sample.csv"

# --- Generate sample data if missing ---
def generate_sample_data():
    # PCAP
    if not os.path.exists(PCAP_PATH):
        os.makedirs(os.path.dirname(PCAP_PATH), exist_ok=True)
        pkt = Ether()/IP(dst="1.2.3.4")/TCP(dport=80)
        wrpcap(PCAP_PATH, [pkt])
        print(f"[+] Sample PCAP created at {PCAP_PATH}")

    # Vulnerabilities
    if not os.path.exists(VULN_PATH):
        os.makedirs(os.path.dirname(VULN_PATH), exist_ok=True)
        with open(VULN_PATH, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=["Vulnerability", "Severity"])
            writer.writeheader()
            writer.writerow({"Vulnerability": "CVE-2025-1234", "Severity": 9})
        print(f"[+] Sample vulnerabilities CSV created at {VULN_PATH}")

    # IOCs are generated by pull_osint_iocs()

# --- Main Pipeline ---
def main():
    print("[+] Generating missing sample data if needed...")
    generate_sample_data()

    print("[+] Pulling OSINT IOCs...")
    iocs = pull_osint_iocs(IOC_PATH)

    print("[+] Parsing PCAP traffic...")
    traffic = parse_pcap(PCAP_PATH)

    print("[+] Correlating IOCs with traffic...")
    matches = correlate_iocs(traffic, iocs)

    print("[+] Scoring risks...")
    score_vulnerabilities(matches, VULN_PATH)

    print("[+] Generating charts and reports...")
    generate_top_ip_chart()

    print("[+] Pipeline completed successfully!")

# --- Entry Point ---
if __name__ == "__main__":
    main()
